#!/bin/bash

number=$1
if [ -e ${HOME}/.config/i3/ws/${number} ]
then
    name=$(cat ${HOME}/.config/i3/ws/${number})
    name="${number}: ${name}"
else
    name=${number}
fi

i3-msg move container to workspace "${name}"
